const official='https://www.letoile-clermont.com/wp-content/uploads/';
const img={
  hero:'https://www.letoile-clermont.com/wp-content/uploads/2026/01/Letoile-Tacos-Campagne-Produit-01-Goodsite-Banniere-scaled.jpg',
  tacos:'https://www.letoile-clermont.com/wp-content/uploads/2024/07/slider-1.jpg',
  burger:'https://www.letoile-clermont.com/wp-content/uploads/2024/07/encart1-large.jpg',
  chicken:'https://www.letoile-clermont.com/wp-content/uploads/2024/07/encart2-large.jpg',
  texmex:'https://www.letoile-clermont.com/wp-content/uploads/2024/07/encart2-large.jpg',
  sandwich:'https://www.letoile-clermont.com/wp-content/uploads/2024/07/encart3-large.jpg',
  fries:'https://www.letoile-clermont.com/wp-content/uploads/2024/07/slider-1.jpg',
  bowl:'https://www.letoile-clermont.com/wp-content/uploads/2026/01/Letoile-Tacos-Campagne-Produit-01-Goodsite-Banniere-scaled.jpg',
  dessert:'https://www.letoile-clermont.com/wp-content/uploads/2024/07/slider-1.jpg'
};
const composer=[['SIMPLE','Taille M • 1 galette, 1 viande','8.00€'],['MAXI','Taille L • 2 galettes, 2 viandes','12.00€'],['MEGA','Taille XL • 3 galettes, 3 viandes','15.00€'],['GIGA','Taille XXL • 4 galettes, 4 viandes','18.00€']];
const menu=[
{cat:'Tacos signatures',name:'O’Majestik',desc:'Sauce fromagère, poulet curry, mozza, boursin, chakchouka.',price:'10.00€',image:img.tacos},{cat:'Tacos signatures',name:'O’Thentik',desc:'Steak, tomates, oignons grillés, poivrons, œuf, emmental, frites.',price:'12.00€',image:img.tacos},{cat:'Tacos signatures',name:'O’Chèvre Miel',desc:'Sauce fromagère, kebab, chèvre miel.',price:'10.00€',image:img.tacos},{cat:'Tacos signatures',name:'O’Spicy',desc:'Viande hachée, onion rings, oignons frits, reblochon, chakchouka, frites.',price:'12.00€',image:img.tacos},{cat:'Tacos signatures',name:'O’Xford',desc:'Sauce fromagère, steak, mozzarella, rostie.',price:'10.00€',image:img.tacos},{cat:'Tacos signatures',name:'O’Rientale',desc:'Merguez, kefta, olives, poivrons, mozza, chakchouka.',price:'12.00€',image:img.tacos},{cat:'Tacos signatures',name:'Montagnard',desc:'Viande au choix, lardons, oignons frits, mozza, reblochon, frites.',price:'10.00€',image:img.tacos},{cat:'Tacos signatures',name:'O’Vergnat',desc:'Tenders, nuggets, bleu, rostie, frites.',price:'12.00€',image:img.tacos},{cat:'Tacos signatures',name:'O’Riginal',desc:'Cordon bleu, poulet pané, oignons frits, raclette.',price:'12.00€',image:img.tacos},{cat:'Tacos signatures',name:'Végétarien',desc:'Galette de pomme de terre, œuf, falafel, frites.',price:'8.00€',image:img.tacos},
{cat:'Tacos sucrés',name:'Tacos Nutella',desc:'Tacos dessert généreux au Nutella.',price:'4.00€',image:img.dessert},{cat:'Tacos sucrés',name:'Tacos Kinder Bueno',desc:'Tacos sucré Kinder Bueno.',price:'5.50€',image:img.dessert},{cat:'Tacos sucrés',name:'Tacos Kit Kat',desc:'Tacos sucré Kit Kat.',price:'5.50€',image:img.dessert},{cat:'Tacos sucrés',name:'Tacos MM’s Nutella',desc:'Tacos sucré MM’s Nutella.',price:'5.50€',image:img.dessert},
{cat:'Burgers',name:'Veggie',desc:'Burger végétarien gourmand.',price:'5.00€',image:img.burger},{cat:'Burgers',name:'Chick’n',desc:'Burger poulet croustillant.',price:'5.00€',image:img.burger},{cat:'Burgers',name:'Cheese',desc:'Classique cheese burger.',price:'5.00€',image:img.burger},{cat:'Burgers',name:'Double Cheese',desc:'Double steak, double plaisir.',price:'6.50€',image:img.burger},{cat:'Burgers',name:'Chèvre Miel',desc:'Fromage de chèvre et touche de miel.',price:'7.00€',image:img.burger},{cat:'Burgers',name:'Baps',desc:'Burger gourmand signature.',price:'7.00€',image:img.burger},{cat:'Burgers',name:'Supreme',desc:'Burger premium généreux.',price:'7.00€',image:img.burger},{cat:'Burgers',name:'Mac',desc:'Burger façon maison.',price:'7.50€',image:img.burger},{cat:'Burgers',name:'Triple Cheese',desc:'Triple dose de gourmandise.',price:'8.00€',image:img.burger},{cat:'Burgers',name:'King',desc:'Burger généreux façon king.',price:'8.00€',image:img.burger},{cat:'Burgers',name:'PSG',desc:'Burger signature.',price:'8.00€',image:img.burger},{cat:'Burgers',name:'Royal Bacon',desc:'Burger royal avec bacon.',price:'7.00€',image:img.burger},{cat:'Burgers',name:'Double Cheese Bacon',desc:'Double cheese avec bacon.',price:'8.00€',image:img.burger},
{cat:'Sandwichs',name:'Sandwich Kebab',desc:'Pain maison ou galette, crudités et sauces.',price:'7.00€',image:img.sandwich},{cat:'Sandwichs',name:'Sandwich Chicken',desc:'Poulet mariné, crudités et sauces.',price:'7.00€',image:img.sandwich},{cat:'Sandwichs',name:'Sandwich Tenders',desc:'Tenders, salade, tomates, oignons.',price:'7.00€',image:img.sandwich},{cat:'Sandwichs signatures',name:'O’Bama',desc:'Sandwich signature maison.',price:'9.00€',image:img.sandwich},{cat:'Sandwichs signatures',name:'Panam',desc:'Sandwich signature gourmand.',price:'9.00€',image:img.sandwich},{cat:'Sandwichs signatures',name:'Radical',desc:'Signature premium XXL.',price:'11.00€',image:img.sandwich},{cat:'Sandwichs signatures',name:'Magistral',desc:'Signature premium XXL.',price:'11.00€',image:img.sandwich},
{cat:'Bowls',name:'Compose ton Bowl — 1 viande',desc:'Frites, sauce fromagère, gratiné mozza, 2 sauces.',price:'8.00€',image:img.bowl},{cat:'Bowls',name:'Compose ton Bowl — 2 viandes',desc:'Frites, sauce fromagère, gratiné mozza, 2 sauces.',price:'10.00€',image:img.bowl},{cat:'Bowls signatures',name:'Indy Bowl',desc:'Bowl signature.',price:'11.00€',image:img.bowl},{cat:'Bowls signatures',name:'Super Bowl',desc:'Bowl très généreux.',price:'15.00€',image:img.bowl},{cat:'Bowls signatures',name:'Big Bowl',desc:'Bowl généreux premium.',price:'15.00€',image:img.bowl},
{cat:'Menus & Box',name:'Menu Duo',desc:'Sandwich kebab + cheese + frites + boisson 33cl.',price:'13.90€',image:img.fries},{cat:'Menus & Box',name:'Menu Gourmand',desc:'Double cheese + cheese + frites + boisson 33cl.',price:'13.90€',image:img.fries},{cat:'Menus & Box',name:'Menu Enfants',desc:'Cheese ou 5 nuggets + frites + boisson 33cl.',price:'6.90€',image:img.fries},{cat:'Menus & Box',name:'Menu Tenders',desc:'6 tenders + frites + boisson 33cl.',price:'8.90€',image:img.chicken},{cat:'Menus & Box',name:'Menu Wings',desc:'6 wings + frites + boisson 33cl.',price:'8.90€',image:img.chicken},{cat:'Menus & Box',name:'Menu Étudiant',desc:'Sandwich ou tortilla kebab + frites + canette 33cl.',price:'6.90€',image:img.sandwich},{cat:'Menus & Box',name:'Box 1',desc:'16 tenders + 4 frites + 1 boisson 1.25L.',price:'23.00€',image:img.chicken},{cat:'Menus & Box',name:'Box 2',desc:'20 wings + 4 frites + 1 boisson 1.25L.',price:'27.00€',image:img.chicken},{cat:'Menus & Box',name:'Box 3',desc:'10 tenders + 10 wings + 4 frites + boisson 1.25L.',price:'27.00€',image:img.chicken},{cat:'Menus & Box',name:'Box 4',desc:'6 tenders + 6 wings + 6 nuggets + 6 mozza sticks + frites + boisson.',price:'30.00€',image:img.chicken},
{cat:'Frites & Barquettes',name:'Frites Cheddar Bacon',desc:'Frites gourmandes cheddar bacon.',price:'4.00€',image:img.fries},{cat:'Frites & Barquettes',name:'Frites Fromagère',desc:'Frites avec sauce fromagère.',price:'3.50€',image:img.fries},{cat:'Frites & Barquettes',name:'Frites',desc:'Petite 2.50€ / Moyenne 3.00€ / Grande 3.50€.',price:'2.50€+',image:img.fries},{cat:'Desserts & Boissons',name:'Cheesecake Cookie',desc:'Dessert gourmand.',price:'3.50€',image:img.dessert},{cat:'Desserts & Boissons',name:'Tarte Daim',desc:'Dessert gourmand.',price:'3.50€',image:img.dessert},{cat:'Desserts & Boissons',name:'Coca 33cl',desc:'Boisson fraîche.',price:'1.80€',image:img.dessert},{cat:'Desserts & Boissons',name:'Monster 50cl',desc:'Boisson énergisante.',price:'3.00€',image:img.dessert}
];
const composerEl=document.getElementById('composerCards');composerEl.innerHTML=composer.map(c=>`<article class="card reveal"><div class="card-img" style="background-image:url('${img.tacos}')"></div><div class="card-body"><h3>${c[0]}</h3><p class="desc">${c[1]}</p><div class="price">${c[2]}</div></div></article>`).join('');
const chipsEl=document.getElementById('chips'),grid=document.getElementById('menuGrid'),search=document.getElementById('search');const cats=['Tous',...new Set(menu.map(i=>i.cat))];let active='Tous';chipsEl.innerHTML=cats.map(c=>`<button class="chip ${c==='Tous'?'active':''}" data-cat="${c}">${c}</button>`).join('');function render(){const q=search.value.toLowerCase();grid.innerHTML=menu.filter(i=>(active==='Tous'||i.cat===active)&&(i.name+i.desc+i.cat).toLowerCase().includes(q)).map(i=>`<article class="card menu-card reveal show"><div class="card-img" style="background-image:url('${i.image}')"></div><div class="card-body"><div class="tag">${i.cat}</div><h3>${i.name}</h3><p class="desc">${i.desc}</p><div class="price">${i.price}</div></div></article>`).join('')}chipsEl.addEventListener('click',e=>{if(e.target.matches('.chip')){active=e.target.dataset.cat;document.querySelectorAll('.chip').forEach(b=>b.classList.toggle('active',b.dataset.cat===active));render()}});search.addEventListener('input',render);render();
const nav=document.getElementById('nav');window.addEventListener('scroll',()=>nav.classList.toggle('scrolled',scrollY>40));document.getElementById('hamburger').addEventListener('click',()=>document.getElementById('navlinks').classList.toggle('open'));document.querySelectorAll('.navlinks a').forEach(a=>a.addEventListener('click',()=>document.getElementById('navlinks').classList.remove('open')));
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
