const MENU = [
  {cat:'Croustiz', img:'mix.jpg', items:[['L’Original','Croustiz généreux, croustillant et sauce maison','9.00€'],['Le Spicy','Version relevée avec notes épicées','9.00€'],['Le Curry','Saveur curry, croustillant et fondant','9.00€']]},
  {cat:'Tacos à composer', img:'tacos.jpg', items:[['Simple Taille M','1 galette, 1 viande, sauce fromagère','8.00€'],['Maxi Taille L','2 galettes, 2 viandes','12.00€'],['Mega Taille XL','3 galettes, 3 viandes','15.00€'],['Giga Taille XXL','4 galettes, 4 viandes','18.00€']]},
  {cat:'Tacos Signatures', img:'wrap.jpg', items:[['O’Majestik','Signature généreux maison','10.00€'],['O’Thentik','Recette premium complète','12.00€'],['O’Chèvre Miel','Chèvre, miel, viande au choix','10.00€'],['O’Spicy','Recette relevée','12.00€'],['O’Xford','Signature maison','10.00€'],['O’Rientale','Saveurs orientales','12.00€'],['Montagnard','Fromage et goût intense','10.00€'],['O’Vergnat','Recette spéciale Clermont','12.00€'],['O’Riginal','La valeur sûre','12.00€'],['Végétarien','Sans viande, gourmand','8.00€']]},
  {cat:'Burgers', img:'burger.jpg', items:[['Veggie','Rostie, cheddar, salade, tomate, oignon','5.00€'],['Chick’n','Chicken pané, cheddar, salade, tomate','5.00€'],['Cheese','Steak, cheddar, salade, tomate','5.00€'],['Double Cheese','2 steaks, 2 cheddars','6.50€'],['Chèvre Miel','Chèvre, miel, steak','7.00€'],['Baps','Burger généreux maison','7.00€'],['Supreme','Burger premium','7.00€'],['Mac','Double saveur maison','7.50€'],['Triple Cheese','3 steaks, 3 cheddars','8.00€'],['King','Burger royal','8.00€'],['PSG','Signature burger','8.00€'],['Royal Bacon','Bacon, cheddar, steak','7.00€'],['Double Cheese Bacon','2 steaks, bacon, cheddar','8.00€']]},
  {cat:'Sandwichs', img:'meat.jpg', items:[['Nugget’s','Pain maison/galette, crudités, sauces','7.00€'],['Kebab','Pain maison/galette, crudités, sauces','7.00€'],['Viande hachée','Pain maison/galette, crudités, sauces','7.00€'],['Chicken','Pain maison/galette, crudités, sauces','7.00€'],['Tenders','Pain maison/galette, crudités, sauces','7.00€'],['Cordon Bleu','Pain maison/galette, crudités, sauces','7.00€'],['O’Bama','Sandwich signature','9.00€'],['Panam','Sandwich signature','9.00€'],['Cowboy','Sandwich signature','9.00€'],['Radical','Sandwich premium','11.00€']]},
  {cat:'Bowls & Box', img:'mix.jpg', items:[['Compose ton Bowl 1 viande','Frites, sauce fromagère, gratiné mozza','8.00€'],['Compose ton Bowl 2 viandes','Frites, sauce fromagère, gratiné mozza','10.00€'],['Indy Bowl','Bowl signature','11.00€'],['Spicy Bowl','Bowl signature relevé','11.00€'],['Super Bowl','Format généreux','15.00€'],['Menu Duo','Menu complet','13.90€'],['Menu Gourmand','Menu complet','13.90€'],['Menu Enfants','Menu enfant','6.90€'],['Box 1','Box à partager','23.00€'],['Box 4','Box familiale','30.00€']]},
  {cat:'Texmex & Frites', img:'tenders.jpg', items:[['Tenders x6','Croustillants','5.50€'],['Wings x6','Ailes épicées','5.50€'],['Nugget’s x10','Poulet croustillant','7.90€'],['Onion rings x8','Rings croustillants','6.90€'],['Sticks Mozza x6','Mozzarella fondante','5.50€'],['Frites cheddar bacon','Frites gourmandes','4.00€'],['Frites fromagère','Sauce fromagère','3.50€'],['Grande frites','Portion généreuse','3.50€']]},
  {cat:'Desserts & Boissons', img:'fries.jpg', items:[['Burger O’ Nutella','Dessert gourmand','2.00€'],['Cheesecake Cookie','Dessert frais','3.50€'],['Tarte Daim','Dessert gourmand','3.50€'],['Tiramisu Chocolat Noisette','Dessert maison','3.50€'],['Coca 33cl','Boisson fraîche','1.80€'],['Oasis Tropical 33cl','Boisson fraîche','1.80€'],['Cristalline 50cl','Eau','1.50€'],['Monster 50cl','Energy drink','3.00€']]}
];
