const IMG={burger:'assets/burger-cheese.jpg',double:'assets/burger-double.jpg',chicken:'assets/burger-chicken.jpg',veggie:'assets/burger-veggie.jpg',tacos:'assets/tacos.jpg',spicy:'assets/tacos-spicy.jpg',sandwich:'assets/sandwich.jpg',bowl:'assets/bowl.jpg',texmex:'assets/texmex.jpg',fries:'assets/fries.jpg',dessert:'assets/dessert.jpg',drink:'assets/drink.jpg',panini:'assets/panini.jpg',salade:'assets/salade.jpg',assiette:'assets/assiette.jpg',croustiz:'assets/croustiz.jpg'};
const tacosComposer={
 sizes:[['Simple Taille M','1 galette, 1 viande','8.00€'],['Maxi Taille L','2 galettes, 2 viandes','12.00€'],['Mega Taille XL','3 galettes, 3 viandes','15.00€'],['Giga Taille XXL','4 galettes, 4 viandes','18.00€']],
 meats:['Tenders','Cordon Bleu','Kefta','Viande hachée','Kebab','Steak','Nuggets','Falafel','Chicken','Merguez','Poulet pané'],
 sauces:['Ketchup','Mayonnaise','Blanche','Harissa','Algérienne','Samourai','Biggy burger','Chili thaï','Curry','Tartare','Andalouse','Barbecue','Poivre'],
 extras:[['Fromages','+1.00€'],['Légumes','+1.00€'],['Gratinages','+2.00€ / +1.50€'],['Frites','+1.00€'],['Canette','+1.50€']]
};
const menu=[
 {cat:'Nos Croustiz',items:[['L’Original','', '9.00€',IMG.croustiz],['Le Spicy','', '9.00€',IMG.spicy],['Le Curry','', '9.00€',IMG.croustiz]]},
 {cat:'Tacos à composer',items:[['Simple','Taille M · 1 galette, 1 viande','8.00€',IMG.tacos],['Maxi','Taille L · 2 galettes, 2 viandes','12.00€',IMG.tacos],['Mega','Taille XL · 3 galettes, 3 viandes','15.00€',IMG.tacos],['Giga','Taille XXL · 4 galettes, 4 viandes','18.00€',IMG.tacos]]},
 {cat:'Tacos Signatures',items:[['O’Majestik','','10.00€',IMG.tacos],['O’Thentik','','12.00€',IMG.tacos],['O’Chèvre Miel','','10.00€',IMG.tacos],['O’Spicy','','12.00€',IMG.spicy],['O’Xford','','10.00€',IMG.tacos],['O’Rientale','','12.00€',IMG.tacos],['Montagnard','','10.00€',IMG.tacos],['O’Vergnat','','12.00€',IMG.tacos],['O’Riginal','','12.00€',IMG.tacos],['Végétarien','','8.00€',IMG.veggie]]},
 {cat:'Tacos Sucrés',items:[['Tacos Nutella','','4.00€',IMG.dessert],['Tacos Kinder Bueno','','5.50€',IMG.dessert],['Tacos Kit Kat','','5.50€',IMG.dessert],['Tacos MM’s Nutella','','5.50€',IMG.dessert]]},
 {cat:'Burgers',items:[['Veggie','Rostie, cheddar, salade, tomate, oignon','5.00€',IMG.veggie],['Chick’n','Chicken pané, cheddar, salade, tomate, oignon','5.00€',IMG.chicken],['Cheese','Steak, cheddar, salade, tomate, oignon','5.00€',IMG.burger],['Double Cheese','2 steaks, 2 cheddars, salade, tomate, oignon','6.50€',IMG.double],['Chèvre Miel','Steak, chèvre, miel, salade, tomate, oignon','7.00€',IMG.burger],['Baps','Steak, 2 cheddars, rostie, salade, tomate, oignon','7.00€',IMG.double],['Supreme','Steak, poulet pané, 2 cheddars, salade, tomate, oignon','7.00€',IMG.double],['Mac','Cordon bleu, bacon, cheddar, salade, tomate, oignon','7.50€',IMG.chicken],['Triple Cheese','3 steaks, 3 cheddars, salade, tomate, oignon','8.00€',IMG.double],['King','Steak, bacon, oeuf, 2 cheddars, salade, tomate, oignon','8.00€',IMG.double],['PSG','Steak, poulet pané, oignon, 3 cheddars, rostie, salade, tomate','8.00€',IMG.double],['Royal Bacon','Steak 100g, bacon, cornichons, oignons frits, 2 cheddar, sauce au choix','7.00€',IMG.double],['Double Cheese Bacon','2 steaks 100g, 2 cheddar, cornichons, 2 tranches de bacon, sauce au choix','8.00€',IMG.double]]},
 {cat:'Sandwichs Classiques',items:['Nugget’s','Kebab','Viande hachée','Chicken','Tenders','Cordon Bleu','Kefta','Merguez','Poulet pané','Falafel','Végé'].map(n=>[n,'Pain maison ou galette, viande au choix, crudités, 2 sauces','7.00€',IMG.sandwich])},
 {cat:'Sandwichs Signatures',items:[['O’Bama','','9.00€',IMG.sandwich],['Panam','','9.00€',IMG.sandwich],['Cowboy','','9.00€',IMG.sandwich],['Veggie Lover','','9.00€',IMG.veggie],['Ideal','','9.00€',IMG.sandwich],['Zlatan','','9.00€',IMG.sandwich],['Turbo','','9.00€',IMG.sandwich],['O’Rientale','','9.00€',IMG.sandwich],['Costo','','9.00€',IMG.sandwich],['Radical','','11.00€',IMG.sandwich],['Magistral','','11.00€',IMG.sandwich]]},
 {cat:'Compose ton Bowl',items:[['1 viande','Frites + sauce fromagère + gratiné mozza + 2 sauces','8.00€',IMG.bowl],['2 viandes','Frites + sauce fromagère + gratiné mozza + 2 sauces','10.00€',IMG.bowl]]},
 {cat:'Bowl Signatures',items:[['Indy Bowl','','11.00€',IMG.bowl],['Spicy Bowl','','11.00€',IMG.spicy],['Exotic Bowl','','11.00€',IMG.bowl],['Tipik Bowl','','11.00€',IMG.bowl],['Mythique Bowl','','11.00€',IMG.bowl],['Crousti Bowl','','11.00€',IMG.bowl],['Veggie Bowl','','11.00€',IMG.veggie],['Kebab Bowl','','11.00€',IMG.bowl],['Crispy Bowl','','11.00€',IMG.bowl],['Super Bowl','','15.00€',IMG.bowl],['Cheese Bowl','','12.00€',IMG.bowl],['Big Bowl','','15.00€',IMG.bowl],['Box Bowl','','8.00€',IMG.bowl]]},
 {cat:'Menus & Box',items:[['Menu Duo','','13.90€',IMG.burger],['Menu Gourmand','','13.90€',IMG.tacos],['Menu Enfants','','6.90€',IMG.burger],['Menu Tenders','','8.90€',IMG.texmex],['Menu Wings','','8.90€',IMG.texmex],['Menu Étudiant','','6.90€',IMG.sandwich],['Box 1','','23.00€',IMG.texmex],['Box 2','','27.00€',IMG.texmex],['Box 3','','27.00€',IMG.texmex],['Box 4','','30.00€',IMG.texmex]]},
 {cat:'Assiettes',items:[['1 viande','Kebab, merguez, tenders, cordon bleu, steak, végé, kefta, chicken chika','12.00€',IMG.assiette],['2 viandes','Kebab, merguez, tenders, cordon bleu, steak, végé, kefta, chicken chika','14.00€',IMG.assiette],['3 viandes','Kebab, merguez, tenders, cordon bleu, steak, végé, kefta, chicken chika','16.00€',IMG.assiette]]},
 {cat:'Texmex',items:[['Tenders','x3 2.90€ · x6 5.50€ · x12 10.90€','',IMG.texmex],['Onion rings','x4 3.50€ · x8 6.90€ · x12 10.90€','',IMG.texmex],['Sticks Mozza','x3 2.90€ · x6 5.50€ · x12 10.90€','',IMG.texmex],['Nugget’s','x5 3.90€ · x10 7.90€ · x15 12.90€','',IMG.texmex],['Falafel','x3 2.90€ · x6 5.50€ · x12 10.90€','',IMG.texmex],['Wings','x3 2.90€ · x6 5.50€ · x12 10.90€','',IMG.texmex],['Bouchée Camembert','x4 3.90€ · x6 5.90€ · x9 7.90€','',IMG.texmex],['Chili Cheese','x4 3.90€ · x6 5.90€ · x9 7.90€','',IMG.texmex]]},
 {cat:'Paninis',items:['3 Fromages','Chicken','Cordon Bleu','Kebab','Kefta','Lardon','Merguez','Nuggets','Poulet pané','Chèvre Miel','Steak','Tenders','Végé'].map(n=>[n,'Options: frites +1€, canette +1.50€','7.00€',IMG.panini])},
 {cat:'Salades',items:[['O’Chèvre Miel','','7.50€',IMG.salade],['O’Rings','','7.50€',IMG.salade],['O’Camembert','','7.50€',IMG.salade]]},
 {cat:'Frites et Barquettes',items:[['Frites Cheddar Bacon','','4.00€',IMG.fries],['Frites Cheddar Oignons Crispy','','4.00€',IMG.fries],['Frites Fromagère Lardons','','4.00€',IMG.fries],['Frites Fromagère','','3.50€',IMG.fries],['Frites Cheddar','','3.50€',IMG.fries],['Frites Cheddar Bacon Onions Crispy','','4.50€',IMG.fries],['Frites Petite','','2.50€',IMG.fries],['Frites Moyenne','','3.00€',IMG.fries],['Frites Grande','','3.50€',IMG.fries],['Barquette Chicken Tikka Curry','','8.00€',IMG.fries],['Barquette Kebab','','8.00€',IMG.fries],['Nuggets Cheddar Onions Crispy','','7.00€',IMG.fries]]},
 {cat:'Desserts',items:[['Burger O’ Nutella','','2.00€',IMG.dessert],['Cheesecake Cookie','','3.50€',IMG.dessert],['Cheesecake Citron','','3.50€',IMG.dessert],['Tarte Daim','','3.50€',IMG.dessert],['Tiramisu Chocolat Noisette','','3.50€',IMG.dessert],['Tiramisu Caramel Spéculos','','3.50€',IMG.dessert]]},
 {cat:'Boissons',items:[['Coca 33cl','','1.80€',IMG.drink],['Coca Zero 33cl','','1.80€',IMG.drink],['Coca Cherry 33cl','','1.80€',IMG.drink],['Fanta 33cl','','1.80€',IMG.drink],['Fuzetea 33cl','','1.80€',IMG.drink],['Hawai 33cl','','1.80€',IMG.drink],['Oasis Tropical 33cl','','1.80€',IMG.drink],['Orangina 33cl','','1.80€',IMG.drink],['Schweppes 33cl','','1.80€',IMG.drink],['Sprite 33cl','','1.80€',IMG.drink],['Tropico 33cl','','1.80€',IMG.drink],['Capri Sun 29cl','','1.80€',IMG.drink],['Cristalline 50cl','','1.50€',IMG.drink],['Monster 50cl','','3.00€',IMG.drink],['Coca 1.25L','','3.50€',IMG.drink]]}
];
