import React, {useMemo, useState} from 'react';
import { createRoot } from 'react-dom/client';
import { motion } from 'framer-motion';
import { MapPin, Phone, Clock, Star, Search, Menu as MenuIcon, X, ShoppingBag, Flame, ChefHat, Sparkles } from 'lucide-react';
import './style.css';

const img=(q,i)=>`https://source.unsplash.com/700x520/?${encodeURIComponent(q)}&sig=letoile-${i}`;

const categories=[
{key:'croustiz',label:'Croustiz'}, {key:'tacos',label:'Tacos à composer'}, {key:'signatures',label:'Tacos signatures'}, {key:'sucre',label:'Tacos sucrés'}, {key:'burgers',label:'Burgers'}, {key:'sandwichs',label:'Sandwichs'}, {key:'bowls',label:'Bowls'}, {key:'menus',label:'Menus & Box'}, {key:'assiettes',label:'Assiettes & Texmex'}, {key:'paninis',label:'Paninis'}, {key:'salades',label:'Salades'}, {key:'frites',label:'Frites & Barquettes'}, {key:'desserts',label:'Desserts'}, {key:'boissons',label:'Boissons'}];
const products=[
['croustiz','L’Original','Croustiz généreux, croustillant et sauce maison.','9.00€','crispy chicken bowl'],['croustiz','Le Spicy','Version relevée avec notes épicées.','9.00€','spicy crispy chicken'],['croustiz','Le Curry','Saveur curry, croustillant et fondant.','9.00€','curry chicken bowl'],
['tacos','Simple Taille M','1 galette, 1 viande, sauce fromagère.','8.00€','french tacos wrap'],['tacos','Maxi Taille L','2 galettes, 2 viandes, généreux.','12.00€','loaded wrap sandwich'],['tacos','Mega Taille XL','3 galettes, 3 viandes, ultra généreux.','15.00€','large tacos wrap'],['tacos','Giga Taille XXL','4 galettes, 4 viandes, format XXL.','18.00€','giant burrito wrap'],
['signatures','O’Majestik','Signature généreuse sauce fromagère.','10.00€','cheesy tacos wrap'],['signatures','O’Thentik','Recette premium généreuse.','12.00€','loaded steak wrap'],['signatures','O’Chèvre Miel','Chèvre, miel, sauce fromagère.','10.00€','goat cheese wrap'],['signatures','O’Spicy','Recette relevée et gourmande.','12.00€','spicy tacos'],['signatures','O’Xford','Steak, mozzarella, rostie.','10.00€','steak cheese wrap'],['signatures','O’Rientale','Merguez, kefta, olives, poivrons.','12.00€','oriental wrap'],['signatures','Montagnard','Reblochon, lardons, oignons frits.','10.00€','mountain cheese sandwich'],['signatures','O’Vergnat','Tenders, nuggets, bleu, rostie.','12.00€','crispy chicken wrap'],['signatures','O’Riginal','Cordon bleu, poulet pané, raclette.','12.00€','raclette chicken wrap'],['signatures','Végétarien','Rostie, œuf, falafel, frites.','8.00€','vegetarian wrap'],
['sucre','Tacos Nutella','Dessert chaud et fondant.','4.00€','nutella crepe'],['sucre','Tacos Kinder Bueno','Kinder Bueno fondant.','5.50€','chocolate dessert wrap'],['sucre','Tacos Kit Kat','Croquant chocolaté.','5.50€','kitkat dessert'],['sucre','Tacos MM’s Nutella','Nutella + MM’s colorés.','5.50€','mms chocolate dessert'],
['burgers','Veggie','Rostie, cheddar, salade, tomate, oignon.','5.00€','veggie burger'],['burgers','Chick’n','Chicken pané, cheddar, salade, tomate.','5.00€','chicken burger'],['burgers','Cheese','Steak, cheddar, salade, tomate, oignon.','5.00€','cheeseburger'],['burgers','Double Cheese','2 steaks, 2 cheddars, crudités.','6.50€','double cheeseburger'],['burgers','Chèvre Miel','Chèvre, miel, steak, salade.','7.00€','goat cheese burger'],['burgers','Baps','Burger généreux façon baps.','7.00€','baps burger'],['burgers','Supreme','Burger premium gourmand.','7.00€','supreme burger'],['burgers','Mac','Double style mac, sauce burger.','7.50€','big mac burger'],['burgers','Triple Cheese','3 steaks, cheddar fondant.','8.00€','triple cheeseburger'],['burgers','King','Burger royal généreux.','8.00€','king burger'],['burgers','PSG','Signature burger spécial.','8.00€','special burger'],['burgers','Royal Bacon','Bacon, steak, cheddar.','7.00€','bacon burger'],['burgers','Double Cheese Bacon','Double steak, bacon, cheddar.','8.00€','double bacon cheeseburger'],
['sandwichs','Kebab','Pain maison ou galette, crudités, sauces.','7.00€','kebab sandwich'],['sandwichs','Chicken','Chicken, salade, tomate, oignons.','7.00€','chicken sandwich'],['sandwichs','Tenders','Tenders croustillants, sauces au choix.','7.00€','crispy chicken sandwich'],['sandwichs','O’Bama','Sandwich signature premium.','9.00€','premium sandwich'],['sandwichs','Cowboy','Signature généreuse façon cowboy.','9.00€','bbq sandwich'],['sandwichs','Magistral','Grand sandwich signature.','11.00€','big steak sandwich'],
['bowls','Compose ton Bowl 1 viande','Frites, sauce fromagère, mozza, sauces.','8.00€','loaded fries bowl'],['bowls','Compose ton Bowl 2 viandes','Double viande, gratiné mozza.','10.00€','meat bowl fries'],['bowls','Indy Bowl','Bowl signature gourmand.','11.00€','chicken rice bowl'],['bowls','Spicy Bowl','Bowl signature relevé.','11.00€','spicy chicken bowl'],['bowls','Veggie Bowl','Version veggie croustillante.','11.00€','vegetarian bowl'],['bowls','Super Bowl','Grand bowl premium.','15.00€','large food bowl'],
['menus','Menu Duo','Sandwich kebab + cheese + frites + boisson.','13.90€','burger fries drink'],['menus','Menu Gourmand','Double cheese + cheese + frites + boisson.','13.90€','two burgers meal'],['menus','Menu Enfants','Cheese ou nuggets + frites + boisson.','6.90€','kids burger meal'],['menus','Menu Tenders','6 tenders + frites + boisson.','8.90€','tenders fries'],['menus','Menu Wings','6 wings + frites + boisson.','8.90€','chicken wings fries'],['menus','Menu Étudiant','Menu petit prix étudiant.','6.90€','student meal burger'],['menus','Box 1','Box généreuse à partager.','23.00€','fast food box'],['menus','Box 2','Box familiale premium.','27.00€','party food box'],['menus','Box 3','Box mix tacos/burgers.','27.00€','sharing platter'],['menus','Box 4','Grande box gourmande.','30.00€','large food platter'],
['assiettes','Assiette 1 viande','Assiette complète avec garniture.','12.00€','kebab plate'],['assiettes','Assiette 2 viandes','Double viande, assiette généreuse.','14.00€','mixed grill plate'],['assiettes','Assiette 3 viandes','Triple viande, format premium.','16.00€','grill platter'],['assiettes','Tenders x6','Tenders croustillants.','5.50€','chicken tenders'],['assiettes','Nugget’s x10','Nuggets dorés.','7.90€','chicken nuggets'],['assiettes','Wings x6','Wings épicées.','5.50€','chicken wings'],['assiettes','Onion rings x8','Onion rings croustillants.','6.90€','onion rings'],['assiettes','Sticks Mozza x6','Mozzarella sticks fondants.','5.50€','mozzarella sticks'],
['paninis','3 Fromages','Panini chaud aux 3 fromages.','7.00€','cheese panini'],['paninis','Chicken','Panini chicken gourmand.','7.00€','chicken panini'],['paninis','Kebab','Panini kebab chaud.','7.00€','kebab panini'],['paninis','Chèvre Miel','Chèvre miel fondant.','7.00€','goat cheese panini'],['paninis','Steak','Panini steak cheddar.','7.00€','steak panini'],
['salades','O’Chèvre Miel','Salade chèvre miel gourmande.','7.50€','goat cheese salad'],['salades','O’Rings','Salade avec onion rings.','7.50€','crispy salad'],['salades','O’Camembert','Salade camembert croustillant.','7.50€','camembert salad'],
['frites','Frites Cheddar Bacon','Frites, cheddar, bacon.','4.00€','loaded fries bacon cheese'],['frites','Frites Fromagère','Sauce fromagère maison.','3.50€','cheese fries'],['frites','Frites Petite','Portion petite.','2.50€','french fries'],['frites','Frites Moyenne','Portion moyenne.','3.00€','crispy fries'],['frites','Frites Grande','Grande portion.','3.50€','large fries'],['frites','Barquette Kebab','Barquette viande kebab.','8.00€','kebab fries box'],['frites','Nuggets Cheddar Onions','Nuggets, cheddar, oignons crispy.','7.00€','loaded nuggets'],
['desserts','Burger O’ Nutella','Mini burger dessert Nutella.','2.00€','nutella dessert'],['desserts','Cheesecake Cookie','Cheesecake cookie.','3.50€','cookie cheesecake'],['desserts','Cheesecake Citron','Cheesecake citron.','3.50€','lemon cheesecake'],['desserts','Tarte Daim','Tarte Daim gourmande.','3.50€','daim cake'],['desserts','Tiramisu Chocolat Noisette','Tiramisu chocolat noisette.','3.50€','chocolate tiramisu'],['desserts','Tiramisu Caramel Spéculos','Tiramisu caramel spéculos.','3.50€','caramel tiramisu'],
['boissons','Coca 33cl','Canette fraîche.','1.80€','coca cola can'],['boissons','Coca Zero 33cl','Canette fraîche.','1.80€','coca zero can'],['boissons','Fanta 33cl','Canette fraîche.','1.80€','orange soda can'],['boissons','Oasis Tropical 33cl','Boisson fruitée.','1.80€','tropical drink'],['boissons','Cristalline 50cl','Eau minérale.','1.50€','water bottle'],['boissons','Monster 50cl','Energy drink.','3.00€','energy drink can'],['boissons','Coca 1.25L','Grande bouteille.','3.50€','cola bottle']
].map((p,i)=>({cat:p[0],name:p[1],desc:p[2],price:p[3],image:img(p[4],i+1)}));

function App(){ const [active,setActive]=useState('all'); const [query,setQuery]=useState(''); const [open,setOpen]=useState(false); const filtered=useMemo(()=>products.filter(p=>(active==='all'||p.cat===active)&&(`${p.name} ${p.desc}`.toLowerCase().includes(query.toLowerCase()))),[active,query]);
return <>
<header className="nav"><a className="brand" href="#home"><span className="logoStar">★</span><b>L'ÉTOILE</b><small>CLERMONT</small></a><nav className={open?'show':''}><a href="#menu">Carte</a><a href="#why">Qualité</a><a href="#gallery">Galerie</a><a href="#contact">Contact</a><a className="order" href="tel:0473905738">Commander</a></nav><button className="hamb" onClick={()=>setOpen(!open)}>{open?<X/>:<MenuIcon/>}</button></header>
<section id="home" className="hero"><div className="glow"></div><motion.div initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} className="heroText"><span className="badge"><Flame size={16}/> Depuis 2010 • Clermont-Ferrand</span><h1>Le goût de <span>l’excellence</span></h1><p>Tacos généreux, burgers premium, bowls gratinés et frites maison dans une ambiance dark red ultra gourmande.</p><div className="actions"><a href="#menu" className="btn primary"><ShoppingBag/> Voir la carte</a><a href="tel:0473905738" className="btn ghost"><Phone/> Appeler</a></div></motion.div><motion.div initial={{opacity:0,scale:.92}} animate={{opacity:1,scale:1}} className="heroFood"><img src={img('burger tacos fries fast food smoke',99)} /><div className="floatCard"><Star/> Viandes premium • Sauces signature</div></motion.div></section>
<section className="stats"><div><b>90+</b><span>Produits</span></div><div><b>14</b><span>Catégories</span></div><div><b>2</b><span>Adresses</span></div><div><b>7j/7</b><span>Ouvert</span></div></section>
<section id="why" className="why"><h2>Pourquoi L'Étoile ?</h2><div className="whyGrid">{[['Viandes de qualité',ChefHat],['Sauces signature',Sparkles],['Frites généreuses',Flame],['Commande rapide',ShoppingBag]].map(([t,Icon])=><article><Icon/><h3>{t}</h3><p>Un rendu premium, clair et moderne pour donner envie dès le premier regard.</p></article>)}</div></section>
<section id="menu" className="menuSec"><div className="sectionTop"><div><span className="eyebrow">Notre carte</span><h2>Menu complet avec images adaptées</h2></div><label className="search"><Search/><input placeholder="Rechercher un produit..." value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="tabs"><button onClick={()=>setActive('all')} className={active==='all'?'on':''}>Tout</button>{categories.map(c=><button onClick={()=>setActive(c.key)} className={active===c.key?'on':''}>{c.label}</button>)}</div><motion.div layout className="grid">{filtered.map((p,i)=><motion.article layout initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="card" key={p.name}><div className="pic"><img loading="lazy" src={p.image}/><span>{categories.find(c=>c.key===p.cat)?.label}</span></div><div className="cardBody"><h3>{p.name}</h3><p>{p.desc}</p><div className="price"><b>{p.price}</b><a href="tel:0473905738">Commander</a></div></div></motion.article>)}</motion.div></section>
<section id="gallery" className="gallery"><h2>Galerie gourmande</h2><div>{['loaded burger','french tacos','crispy fries','dessert chocolate','chicken wings','kebab sandwich'].map((q,i)=><img src={img(q,150+i)} />)}</div></section>
<section id="contact" className="contact"><div><span className="eyebrow">Contact</span><h2>Deux adresses à Clermont-Ferrand</h2><p><MapPin/> 29 Rue Ballainvilliers, 63000 Clermont-Ferrand</p><p><Phone/> <a href="tel:0473905738">04 73 90 57 38</a></p><p><MapPin/> 2 Rue Debay Facy, 63000 Clermont-Ferrand</p><p><Phone/> <a href="tel:0463082410">04 63 08 24 10</a></p><p><Clock/> Ouvert 7j/7 — 10h00 → 01h00</p></div><iframe src="https://www.google.com/maps?q=29%20Rue%20Ballainvilliers%2063000%20Clermont-Ferrand&output=embed"></iframe></section>
<footer><b>★ L'ÉTOILE CLERMONT</b><span>Site premium prêt GitHub / Netlify — images stock non officielles, faciles à remplacer.</span></footer>
</>}
createRoot(document.getElementById('root')).render(<App/>);
